config/routes.rb
Rails.application.routes.draw do

  #
  # Shoppe admin interface
  #
  mount Shoppe::Engine => "/shoppe"
  
  #
  # Product browising
  #
  get 'products' => 'products#categories', :as => 'catalogue'
  get 'products/filter' => 'products#filter', :as => 'product_filter'
  get 'products/:category_id' => 'products#index', :as => 'products'
  get 'products/:category_id/:product_id' => 'products#show', :as => 'product'
  post 'products/:category_id/:product_id/buy' => 'products#add_to_basket', :as => 'buy_product'
  
  #
  # Order status
  #
  get 'order/:token' => 'orders#status', :as => 'order_status'

  #
  # Basket
  #
  get 'basket' => 'orders#show', :as => 'basket'
  delete 'basket' => 'orders#destroy', :as => 'empty_basket'
  post 'basket/:order_item_id' => 'orders#change_item_quantity', :as => 'adjust_basket_item_quantity'
  delete 'basket/:order_item_id' => 'orders#change_item_quantity'
  delete 'basket/delete/:order_item_id' => 'orders#remove_item', :as => 'remove_basket_item'
  
  #
  # Checkout
  #
  match 'checkout' => 'orders#checkout', :as => 'checkout', :via => [:get, :patch]
  match 'checkout/delivery' => 'orders#change_delivery_service', :as => 'change_delivery_service', :via => [:post]
  match 'checkout/pay' => 'orders#payment', :as => 'checkout_payment', :via => [:get, :patch]
  match 'checkout/confirm' => 'orders#confirmation', :as => 'checkout_confirmation', :via => [:get, :patch]
  
  #
  # Static pages
  #
  get ':action', :controller => 'pages', :as => 'page'
  
  # 
  # Homepage
  #
  root :to => 'pages#home'
  
end

app/views/shared/_basket.html.erb
<div class="basket">
  <% if has_order? && current_order.has_items? %>
    <p class="quantity"><b><%=pluralize current_order.total_items, 'item'%></b> in your shopping bag</p>
    <p class="amount"><b><%=number_to_currency current_order.total_before_tax%></b> (ex. tax &amp; delivery)</p>
    <p class="buttons">
      <%= link_to "View my bag", basket_path %>
      <%= link_to "Checkout", checkout_path, :class => 'checkout' %>
    </p>
  <% else %>
    <p class="empty"><b>Your shopping bag is empty.</b> </p>
    <p class="empty">How dare it be?! Why not add some stuff to it?</p>
  <% end %>
</div>

app/views/shared/_order_items.html.erb
<table class="orderItems">
  <thead>
    <tr>
      <td>Qty</td>
      <td>Item</td>
      <td>Price</td>
      <td>
        <%= Shoppe.settings.tax_name %>
      </td>
      <td>Sub-Total</td>
    </tr>
  </thead>
  <tbody>
    <% for item in order.order_items %>
      <tr>
        <td class="quantity">
          <% unless defined?(readonly) %>
            <span>
              <%= link_to "+", adjust_basket_item_quantity_path(item.id), :method => :post, :class => 'ajax' %>
              <%= link_to "-", adjust_basket_item_quantity_path(item.id), :method => :delete, :class => 'ajax' %>
            </span>
          <% end %>
          <%= item.quantity %>
        </td>
        <td class="product">
          <%= item.ordered_item.full_name %>
          <% unless defined?(readonly) %>
            <%= link_to "Delete", remove_basket_item_path(item), :method => :delete, :class => 'delete ajax' %>
          <% end %>
        </td>
        <td class="money price">
          <%= number_to_currency item.sub_total %>
        </td>
        <td class="money tax">
          <%= number_to_currency item.tax_amount %>
        </td>
        <td class="money total">
          <%= number_to_currency item.total %>
        </td>
      </tr>
    <% end %>
  </tbody>
  <tfoot>
    <% if order.delivery_service %>
      <tr class="delivery">
        <td class="method" colspan="4">
          <% if defined?(readonly) %>
            <%= order.delivery_service.name %>
          <% else %>
            <%= form_tag change_delivery_service_path do  %>
              <%= select_tag 'delivery_service', options_from_collection_for_select(order.available_delivery_services, :id, :name, order.delivery_service.id) %>
            <% end %>
          <% end %>
        </td>
        <td class="money">
          <%= number_to_currency order.delivery_price %>
        </td>
      </tr>
    <% end %>
    <tr class="subtotal">
      <td colspan="4">Total (excluding <%=Shoppe.settings.tax_name%>)</td>
      <td class="money">
        <%= number_to_currency order.total_before_tax %>
      </td>
    </tr>
    <tr class="tax">
      <td colspan="4">
        <%= Shoppe.settings.tax_name %>
      </td>
      <td class="money">
        <%= number_to_currency order.tax %>
      </td>
    </tr>
    <tr class="total">
      <td colspan="4">Total</td>
      <td class="money">
        <%= number_to_currency order.total %>
      </td>
    </tr>
  </tfoot>
</table>

app/views/shared/_product_list.html.erb
<ul class="products">
  <% for product in products %>
    <li>
      <div class="img" style="<%=product.default_image ? "background-image:url(#{product.default_image.path})" : ''%>"></div>
      <h4>
        <%= link_to product.name, product_path(product.product_category.permalink, product.permalink) %>
      </h4>
      <p class="info">
        <%= truncate product.short_description, :length => 90 %>
      </p>
      <p class="buttons">
        <%= link_to "Info", product_path(product.product_category.permalink, product.permalink) %>
        <% if product.orderable? %>
          <%= link_to "Add", buy_product_path(product.product_category.permalink, product.permalink), :class => 'add', :method => :post %>
        <% end %>
      </p>
      <p class="price">
        <%= number_to_currency product.price %>
      </p>
    </li>
  <% end %>
</ul>

app/views/shared/_reasons.html.erb
<ul class="reasons">
  <li class="support">
    <h4>Free technical support</h4>
    <p>We'll help you get your phone working. Just call or e-mail us.</p>
  </li>
  <li class="quality">
    <h4>Quality assurance</h4>
    <p>We check all the produts we ship so you can rely on us.</p>
  </li>
  <li class="delivery">
    <h4>Next day delivery</h4>
    <p>Order before 4pm and your order will be with you the next business day.</p>
  </li>
</ul>